#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 23, 2020 11:06:16 AM +0530  platform: Windows NT

import sys
import time
import os
import pathlib

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def ExitButton_LeftClick(p1):
    print('Fuse_support.ExitButton_LeftClick')
    sys.stdout.flush()
    destroy_window()

def Scan(p1):
    print('Fuse_support.Scan')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Fuse
    Fuse.vp_start_gui()




