# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pe47jeTkfnxPT8zv8-ZsxAWHH7fg3G9U
"""

import re
import datetime



def time_compare(date1,time1,date2,time2):
	d1=datetime.date(int(date1[0]),int(date1[1]),int(date1[2]))
	d2=datetime.date(int(date2[0]),int(date2[1]),int(date2[2]))
	t1=datetime.time(int(time1[0]),int(time1[1]),int(time1[2]))
	t2=datetime.time(int(time2[0]),int(time2[1]),int(time2[2]))
	if(d1>d2):
		return False
	elif(d1==d2 and t1<t2):
		return False
	else:
		return True	
  
	def log_processing():
	file = open('../logfile.txt','r')
	t_file=open('./files/time.txt')
	file2 = open('./files/newlogfile.txt','w+')
	file2.truncate()
	time_stamp=str(t_file.readlines())
	year=str(time_stamp[2]+time_stamp[3]+time_stamp[4]+time_stamp[5])
	month=str(time_stamp[7]+time_stamp[8])
	day=str(time_stamp[10]+time_stamp[11])
	date=[]
	date.append(year)
	date.append(month)
	date.append(day)
	hour=str(time_stamp[13]+time_stamp[14])
	minute=str(time_stamp[16]+time_stamp[17])
	sec=str(time_stamp[19]+time_stamp[20])
	time=[]
	time.append(hour)
	time.append(minute)
	time.append(sec)
	t_file.close()
	t_file=open('./files/time.txt','w')
	t_file.truncate()
	t_file.write(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
	t_file.close()
	list = []
	Lines = file.readlines()
	n=len(Lines)-1
	count=0

	for i in range(n,0,-1):
		log=Lines[i]
		words = log.split()
		ts=words[0]
		date1=ts.split('-')
		ts=words[1]
		h=str(ts[0]+ts[1])
		m=str(ts[3]+ts[4])
		s=str(ts[6]+ts[7])
		time1=[]
		time1.append(h)
		time1.append(m)
		time1.append(s)	  
		if(re.search("write+|mknode+",log)):
			if(not time_compare(date,time,date1,time1)):
				break
			if(words[3] =="write"):
				addr=words[7] 
			elif(words[3]=="mknode"):
				addr=words[4]
			if(addr in list):
				continue
			else:
				list.append(addr)  
			count+=1
		      
	for i in list:
		  file2.write(i+"\n")
		  
	file2.close()
	file.close()
	t_file.close()


